// Claude model catalog: the one place Ikenga names Claude models and prices.
//
// Every runtime default (the shell's Claude launch, the engine pkg manifest,
// the model picker, the cost meter and launch copy) reads from this table so
// no surface hard-codes a model id. A JSON copy ships at `schemas/models.json`
// (generated by `pnpm generate:schemas`) for Rust and for manifests.
//
// Prices are USD per million tokens on the Claude API (first party, global
// routing). `cacheWritePerMtok` is the 5-minute cache write; the 1-hour write is
// 2x base input and isn't tracked here. Every row was checked against the
// source named in its `source` field on the `pricingVerifiedAt` date. Re-check
// the published pricing page before changing a number; never price from memory.

import { z } from 'zod';

/** Claude Code `--model` alias for the tier, and groundwork's tier names. */
export const ModelTierAliasSchema = z.enum(['opus', 'sonnet', 'haiku', 'fable']);
export type ModelTierAlias = z.infer<typeof ModelTierAliasSchema>;

/** The launch roles that pick a default model when the caller names none. */
export const ModelRoleSchema = z.enum(['chi', 'pane', 'plan']);
export type ModelRole = z.infer<typeof ModelRoleSchema>;

/** Per-million-token prices in USD. `null` means not yet verified. */
export const ModelPricingSchema = z
  .object({
    inPerMtok: z.number().nonnegative().nullable(),
    outPerMtok: z.number().nonnegative().nullable(),
    cacheReadPerMtok: z.number().nonnegative().nullable(),
    /** 5-minute cache write. */
    cacheWritePerMtok: z.number().nonnegative().nullable(),
  })
  .strict();
export type ModelPricing = z.infer<typeof ModelPricingSchema>;

export const ModelCatalogEntrySchema = z
  .object({
    /** Exact Claude API model id, e.g. `claude-sonnet-5-5`. */
    id: z.string().regex(/^claude-[a-z]+-[0-9]+(-[0-9]+)*$/),
    alias: ModelTierAliasSchema,
    /** Human name, e.g. `Claude Sonnet 5.5`. */
    family: z.string().min(1),
    /** Ordering within the line-up: 1 is the most capable. */
    tier: z.number().int().positive(),
    contextTokens: z.number().int().positive(),
    pricing: ModelPricingSchema,
    /** ISO date (YYYY-MM-DD) the pricing row was last checked. */
    pricingVerifiedAt: z.string().regex(/^\d{4}-\d{2}-\d{2}$/),
    /** Where the pricing row was checked. */
    source: z.string().min(1),
    /** Roles this model is the default for. Each role has exactly one. */
    defaultFor: z.array(ModelRoleSchema).optional(),
  })
  .strict();
export type ModelCatalogEntry = z.infer<typeof ModelCatalogEntrySchema>;

export const ModelCatalogSchema = z
  .array(ModelCatalogEntrySchema)
  .superRefine((rows, ctx) => {
    const ids = new Set<string>();
    const aliases = new Set<string>();
    const roleOwners = new Map<string, string>();
    for (const row of rows) {
      if (ids.has(row.id)) ctx.addIssue({ code: 'custom', message: `duplicate id ${row.id}` });
      ids.add(row.id);
      if (aliases.has(row.alias)) ctx.addIssue({ code: 'custom', message: `duplicate alias ${row.alias}` });
      aliases.add(row.alias);
      for (const role of row.defaultFor ?? []) {
        const owner = roleOwners.get(role);
        if (owner) ctx.addIssue({ code: 'custom', message: `role ${role} defaults to both ${owner} and ${row.id}` });
        roleOwners.set(role, row.id);
      }
    }
    for (const role of ModelRoleSchema.options) {
      if (!roleOwners.has(role)) ctx.addIssue({ code: 'custom', message: `role ${role} has no default model` });
    }
  });
export type ModelCatalog = z.infer<typeof ModelCatalogSchema>;

const PRICING_SOURCE =
  'https://platform.claude.com/docs/en/about-claude/pricing (Model pricing table), cross-checked with the claude-api skill reference (Claude Code 2.1.289)';
const VERIFIED = '2026-10-04';

/**
 * The catalog. Role defaults (plan 2026-10-04-claude-platform-uplift, Round 2):
 * Sonnet 5.5 for Chi and everyday panes, Opus 5.5 for plan / review /
 * orchestrate. Fable 5.1 is listed but is no role's default.
 */
export const MODEL_CATALOG: readonly ModelCatalogEntry[] = Object.freeze([
  {
    id: 'claude-fable-5-1',
    alias: 'fable',
    family: 'Claude Fable 5.1',
    tier: 1,
    contextTokens: 1_000_000,
    pricing: { inPerMtok: 10, outPerMtok: 50, cacheReadPerMtok: 0.25, cacheWritePerMtok: 12.5 },
    pricingVerifiedAt: VERIFIED,
    source: PRICING_SOURCE,
  },
  {
    id: 'claude-opus-5-5',
    alias: 'opus',
    family: 'Claude Opus 5.5',
    tier: 2,
    contextTokens: 1_000_000,
    pricing: { inPerMtok: 4, outPerMtok: 20, cacheReadPerMtok: 0.2, cacheWritePerMtok: 5 },
    pricingVerifiedAt: VERIFIED,
    source: PRICING_SOURCE,
    defaultFor: ['plan'],
  },
  {
    id: 'claude-sonnet-5-5',
    alias: 'sonnet',
    family: 'Claude Sonnet 5.5',
    tier: 3,
    contextTokens: 1_000_000,
    pricing: { inPerMtok: 2, outPerMtok: 10, cacheReadPerMtok: 0.2, cacheWritePerMtok: 2.5 },
    pricingVerifiedAt: VERIFIED,
    source: PRICING_SOURCE,
    defaultFor: ['chi', 'pane'],
  },
  {
    id: 'claude-haiku-4-5',
    alias: 'haiku',
    family: 'Claude Haiku 4.5',
    tier: 4,
    contextTokens: 200_000,
    pricing: { inPerMtok: 1, outPerMtok: 5, cacheReadPerMtok: 0.1, cacheWritePerMtok: 1.25 },
    pricingVerifiedAt: VERIFIED,
    source: PRICING_SOURCE,
  },
]);

/** Model id used when neither a model nor a role is given (the `pane` default). */
export const DEFAULT_MODEL_ID = 'claude-sonnet-5-5' as const;

/** groundwork tier alias → catalog row, so groundwork never hard-codes ids. */
export const MODEL_TIER_ALIASES: Readonly<Record<ModelTierAlias, ModelCatalogEntry>> = Object.freeze(
  Object.fromEntries(MODEL_CATALOG.map((row) => [row.alias, row])) as Record<ModelTierAlias, ModelCatalogEntry>,
);

/** The default catalog row for a launch role. */
export function defaultModelFor(role: ModelRole): ModelCatalogEntry {
  const row = MODEL_CATALOG.find((r) => r.defaultFor?.includes(role));
  // ModelCatalogSchema guarantees every role has an owner; the test suite parses MODEL_CATALOG.
  if (!row) throw new Error(`no default model for role ${role}`);
  return row;
}

/**
 * Finds a row by exact id or by tier alias (`opus`, `sonnet`, `haiku`,
 * `fable`). Returns `undefined` for anything else, including retired ids.
 */
export function findModel(idOrAlias: string): ModelCatalogEntry | undefined {
  const rows = MODEL_CATALOG;
  return rows.find((r) => r.id === idOrAlias) ?? rows.find((r) => r.alias === idOrAlias);
}

/** Token counts for one request or session, as reported in API `usage`. */
export interface ModelUsage {
  inputTokens?: number;
  outputTokens?: number;
  cacheReadTokens?: number;
  /** 5-minute cache writes. */
  cacheWriteTokens?: number;
}

/**
 * USD cost of `usage` on a catalog model. Returns `null` when the model isn't
 * in the catalog or a price the usage needs is unverified.
 */
export function estimateCostUsd(idOrAlias: string, usage: ModelUsage): number | null {
  const row = findModel(idOrAlias);
  if (!row) return null;
  const parts: Array<[number | undefined, number | null]> = [
    [usage.inputTokens, row.pricing.inPerMtok],
    [usage.outputTokens, row.pricing.outPerMtok],
    [usage.cacheReadTokens, row.pricing.cacheReadPerMtok],
    [usage.cacheWriteTokens, row.pricing.cacheWritePerMtok],
  ];
  let total = 0;
  for (const [tokens, price] of parts) {
    if (!tokens) continue;
    if (price === null) return null;
    total += (tokens * price) / 1_000_000;
  }
  return total;
}

// ── JSON copy (`schemas/models.json`) ───────────────────────────────────────

/** `$id` of the JSON Schema that describes `schemas/models.json`. */
export const MODEL_CATALOG_SCHEMA_ID = 'https://registry.ikenga.dev/schemas/models/catalog-v1.json';

/**
 * Shape of the generated `schemas/models.json`: the catalog rows plus the
 * resolved role defaults and tier aliases, so readers that can't run this
 * module (the Rust shell, manifests) don't have to re-derive them.
 */
export const ModelCatalogFileSchema = z
  .object({
    $schema: z.literal(MODEL_CATALOG_SCHEMA_ID),
    version: z.literal(1),
    /** Unit of every `pricing` field. */
    pricingUnit: z.literal('USD per million tokens'),
    defaultModel: z.string(),
    /** Role → model id. */
    roles: z.record(ModelRoleSchema, z.string()),
    /** Tier alias → model id. */
    aliases: z.record(ModelTierAliasSchema, z.string()),
    models: ModelCatalogSchema,
  })
  .strict();
export type ModelCatalogFile = z.infer<typeof ModelCatalogFileSchema>;

/** Builds the document written to `schemas/models.json`. Pure. */
export function buildModelCatalogFile(): ModelCatalogFile {
  const roles = Object.fromEntries(ModelRoleSchema.options.map((r) => [r, defaultModelFor(r).id])) as Record<ModelRole, string>;
  const aliases = Object.fromEntries(
    ModelTierAliasSchema.options.map((a) => [a, MODEL_TIER_ALIASES[a].id]),
  ) as Record<ModelTierAlias, string>;
  return {
    $schema: MODEL_CATALOG_SCHEMA_ID,
    version: 1,
    pricingUnit: 'USD per million tokens',
    defaultModel: DEFAULT_MODEL_ID,
    roles,
    aliases,
    models: MODEL_CATALOG.map((row) => ({ ...row, pricing: { ...row.pricing } })),
  };
}
